SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_COLOR = "black"
FPS = 60

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_COLOR = "white"
ASTEROID_LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_COLOR = "white"
PLAYER_LINE_WIDTH = 2
PLAYER_SPAWN_POINT = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5
SHOT_COLOR = "red"
SHOT_LINE_WIDTH = 2